# syntax=docker/dockerfile:1
ARG ARCH=arm32v7/
FROM ${ARCH}ubuntu:18.04
RUN apt-get --reinstall install bash -y
RUN apt-get update -y
RUN apt-get install curl -y
COPY . /app
CMD python /app/app.py

# docker build -f "Dockerfile.arm32v7" -t test:dev .